In [2]:
import pandas as pd
import numpy as np

In [3]:
df2 = pd.read_csv('benz.csv')

In [4]:
df2

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4207,8415,87.48,al,r,e,f,d,aa,l,u,...,0,0,0,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [5]:
# to display first 5 columns
df2.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [6]:
# to display last 5 columns
df2.tail()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4207,8415,87.48,al,r,e,f,d,aa,l,u,...,0,0,0,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [7]:
# info fucntion give the complete information of df
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), str(8)
memory usage: 12.1 MB

In [8]:
# describe is used to gives result count, mean std, min  25%,50%,75% max
df2.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
df2['X0']

0        k
1        k
2       az
3       az
4       az
        ..
4204    ak
4205     j
4206    ak
4207    al
4208     z
Name: X0, Length: 4209, dtype: str

In [16]:
# this returns the count of repeating
df2['X0'].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
ai     34
m      34
e      32
ba     27
at     25
a      21
ax     19
am     18
aq     18
i      18
u      17
l      16
aw     16
ad     14
k      11
b      11
au     11
as     10
r      10
bc      6
ao      4
c       3
q       2
aa      2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [24]:
df2[df2['y']>100]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
6,24,128.76,al,r,e,f,d,f,h,s,...,0,0,0,0,0,0,0,0,0,0
8,27,108.67,w,s,as,e,d,f,i,h,...,1,0,0,0,0,0,0,0,0,0
9,30,126.99,j,b,aq,c,d,f,a,e,...,0,0,1,0,0,0,0,0,0,0
10,31,102.09,h,r,r,f,d,f,h,p,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4202,8402,123.34,ap,l,s,c,d,aa,d,r,...,0,0,0,0,0,0,0,0,0,0
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [32]:
df2[df2['y']<75]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
91,197,73.70,az,y,as,c,d,j,j,q,...,0,0,0,0,0,0,1,0,0,0
321,639,74.00,az,l,n,f,d,i,g,s,...,0,0,0,0,0,0,0,0,0,0
360,713,74.28,az,m,r,f,d,d,i,s,...,0,0,0,1,0,0,0,0,0,0
368,732,73.34,az,v,n,f,d,d,j,f,...,0,0,0,1,0,0,0,0,0,0
591,1149,73.40,bc,y,ac,c,d,c,j,p,...,0,0,0,0,0,0,1,0,0,0
669,1300,74.53,az,y,e,c,d,c,j,m,...,0,0,0,0,0,0,1,0,0,0
689,1342,74.20,az,y,n,c,d,c,j,m,...,0,0,0,0,0,0,1,0,0,0
1119,2217,74.54,az,y,b,c,d,ab,j,l,...,0,0,0,0,0,0,1,0,0,0
1158,2302,73.59,az,w,n,f,d,ab,l,f,...,0,0,0,0,0,0,0,0,0,0
1458,2902,73.15,az,l,n,f,d,ac,j,s,...,0,0,0,0,0,0,0,0,0,0
1466,2915,74.10,az,t,n,c,d,ac,l,r,...,0,0,0,0,0,0,1,0,0,0
1512,3022,73.45,az,w,as,f,d,ad,j,c,...,0,0,0,1,0,0,0,0,0,0
1594,3185,72.11,az,s,as,f,d,ad,j,n,...,0,0,0,1,0,0,0,0,0,0
1788,3588,74.35,az,m,aq,c,d,ae,j,v,...,0,0,0,0,0,0,1,0,0,0
1803,3616,72.94,az,l,n,f,d,ae,a,b,...,0,0,0,0,0,0,0,0,0,0
1871,3747,72.50,az,l,n,f,d,ah,g,s,...,0,0,0,0,0,0,0,0,0,0
1886,3772,74.86,az,v,n,f,d,ah,i,j,...,0,0,0,0,0,0,0,0,0,0
1898,3802,74.77,az,v,n,f,d,ah,l,f,...,0,0,0,0,0,0,0,0,0,0
1956,3903,73.89,az,l,n,f,d,ah,g,s,...,0,0,0,0,0,0,0,0,0,0
1968,3919,74.20,az,h,n,f,d,l,i,n,...,0,0,0,0,0,0,0,0,0,0
2167,4334,73.79,az,l,n,f,d,k,g,s,...,0,0,0,0,0,0,0,0,0,0
2363,4734,74.43,az,l,n,f,d,n,g,w,...,0,0,0,0,0,0,0,0,0,0
2392,4801,74.87,az,v,n,f,d,n,a,s,...,0,0,0,0,0,0,0,0,0,0
2511,5031,74.66,az,s,h,f,d,n,d,c,...,0,0,0,1,0,0,0,0,0,0
2541,5090,74.76,az,s,e,f,d,n,i,v,...,0,0,0,1,0,0,0,0,0,0
2717,5433,73.71,az,l,n,f,d,m,j,w,...,0,0,0,1,0,0,0,0,0,0
2906,5821,74.50,az,y,aq,c,d,p,j,w,...,0,0,0,0,0,0,1,0,0,0
2926,5865,73.02,az,s,n,c,d,p,d,f,...,0,0,0,0,0,0,1,0,0,0
2942,5899,74.99,az,s,n,f,d,p,g,r,...,0,0,0,1,0,0,0,0,0,0
2965,5948,74.79,az,s,e,f,d,p,j,k,...,0,0,0,1,0,0,0,0,0,0
3109,6237,73.52,az,n,as,c,d,q,d,s,...,0,0,0,0,0,0,1,0,0,0
3128,6266,73.53,az,v,n,f,d,q,l,f,...,0,0,0,0,0,0,0,0,0,0
3231,6456,74.22,az,t,n,f,d,s,j,s,...,0,0,0,0,0,0,0,0,0,0
3277,6539,74.27,az,v,ak,f,d,s,i,i,...,0,0,0,1,0,0,0,0,0,0
3385,6748,74.99,az,v,n,f,d,s,g,f,...,0,0,0,1,0,0,0,0,0,0
3406,6796,73.74,az,v,n,f,d,r,j,j,...,0,0,0,1,0,0,0,0,0,0
3499,6980,74.87,az,v,n,f,d,r,a,n,...,0,0,0,1,0,0,0,0,0,0
3521,7035,73.24,az,s,n,f,d,r,a,n,...,0,0,0,1,0,0,0,0,0,0
3575,7153,73.83,az,h,as,f,d,r,g,y,...,0,0,0,1,0,0,0,0,0,0
3592,7196,74.17,az,v,n,f,d,r,g,f,...,0,0,0,1,0,0,0,0,0,0
3895,7812,73.36,az,l,e,f,d,w,l,b,...,0,0,0,1,0,0,0,0,0,0
3950,7920,73.76,az,v,n,f,d,w,j,j,...,0,0,0,0,0,0,0,0,0,0
3973,7969,74.62,az,l,n,f,d,w,a,n,...,0,0,0,1,0,0,0,0,0,0
3983,7987,74.08,az,v,n,f,d,w,g,f,...,0,0,0,1,0,0,0,0,0,0
4019,8060,74.75,az,w,n,f,d,w,k,j,...,0,0,0,0,0,0,0,0,0,0
4101,8209,73.25,az,l,n,f,d,aa,g,s,...,0,0,0,1,0,0,0,0,0,0

In [36]:
df2[df2['y']<75].head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
91,197,73.70,az,y,as,c,d,j,j,q,...,0,0,0,0,0,0,1,0,0,0
321,639,74.00,az,l,n,f,d,i,g,s,...,0,0,0,0,0,0,0,0,0,0
360,713,74.28,az,m,r,f,d,d,i,s,...,0,0,0,1,0,0,0,0,0,0
368,732,73.34,az,v,n,f,d,d,j,f,...,0,0,0,1,0,0,0,0,0,0
591,1149,73.40,bc,y,ac,c,d,c,j,p,...,0,0,0,0,0,0,1,0,0,0

In [23]:
df2[df2['y']>200]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
883,1770,265.32,y,r,ai,f,d,ag,l,t,...,0,0,0,0,0,0,0,0,0,0

# To read the file from RAM/memory for better performance, below are the two ways

# Use cases of StringIO
- Temporary text storage
- csv processing
- Capturing printed output
- Testing file operations without creating files

### Example: Reading csv from memory

# Use cases of BytesIO
- Image processing
- Audio/video handling
- File uploads/downloads
- Working with API's
- Machine learning model files

### Example: Image Handling

# Difference between String IO and Bytes IO

| Feature | StringIO | BytesIO|
|--- | --- | --- |
| Data Type | Text('str') | Binary ('bytes')|
| works like | Text file | Binary file |
| Input Example | "Hello" | b"Hello" |
| common Use | CSV/Text | Images/PDFs |

- stringIO --> notebook for text
- BytesIO --> storage box for binary files
- Both are virtual files in RAM

In [38]:
# to import StringIO,BytesIO, we need to import IO library
from io import StringIO,BytesIO

In [40]:
data = ('col1,col2,col3\n'
        'a,b,1\n'
        'c,d,2\n'
        'e,f,3')

In [41]:
type(data)

str

In [45]:
# to read the file in pandas
pd.read_csv(StringIO(data))

  col1 col2  col3
0    a    b     1
1    c    d     2
2    e    f     3

In [ ]:
# get specific columns
df = pd.read_csv(StringIO(data),usecols=['col1','col2'])
print(df)

  col1 col2
0    a    b
1    c    d
2    e    f

In [50]:
df.to_csv('test2.csv')

In [51]:
#Specifying columns data types
data = ('a,b,c,d\n'
        '1,2,3,4\n'
        '5,6,7,8\n'
        '9,10,11,12')

In [53]:
print(data)
print(type(data))

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11,12
<class 'str'>

In [55]:
df = pd.read_csv(StringIO(data))
print(df)

   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [56]:
# to make the columns as string 
df = pd.read_csv(StringIO(data),dtype='object')
print(df)

   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [57]:
df['a']

0    1
1    5
2    9
Name: a, dtype: object

In [60]:
# I want to make column b as Int and c as string

df = pd.read_csv(StringIO(data),dtype={'b':int,'c':float})
print(df)

   a   b     c   d
0  1   2   3.0   4
1  5   6   7.0   8
2  9  10  11.0  12

In [ ]:
# to check datatypes for all rows in df
df.dtypes

a      int64
b      int64
c    float64
d      int64
dtype: object

In [67]:
data = ('indx,a,b,c\n'
        '4,apple,bat,5.7\n'
        '8,orange,cow,10')
print(data)

indx,a,b,c
4,apple,bat,5.7
8,orange,cow,10

In [68]:
pd.read_csv(StringIO(data))

   indx       a    b     c
0     4   apple  bat   5.7
1     8  orange  cow  10.0

In [71]:
# to make the first column as Index, below
pd.read_csv(StringIO(data),index_col=0)

           a    b     c
indx
4      apple  bat   5.7
8     orange  cow  10.0

In [72]:
data = ('indx,a,b,c\n'
        '4,apple,bat,5\n'
        '8,orange,cow,')
print(data)

indx,a,b,c
4,apple,bat,5
8,orange,cow,

In [73]:
pd.read_csv(StringIO(data))

   indx       a    b    c
0     4   apple  bat  5.0
1     8  orange  cow  NaN

In [74]:
pd.read_csv(StringIO(data),index_col=False)

   indx       a    b    c
0     4   apple  bat  5.0
1     8  orange  cow  NaN

In [78]:
data = ('a,b,c\n'
        '4,apple,bat,\n'
        '8,orange,cow,')
print(data)

a,b,c
4,apple,bat,
8,orange,cow,

In [79]:
pd.read_csv(StringIO(data))

        a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [80]:
pd.read_csv(StringIO(data),index_col=False)

   a       b    c
0  4   apple  bat
1  8  orange  cow

In [82]:
pd.read_csv(StringIO(data),usecols=['b','c'],index_col=False)

        b    c
0   apple  bat
1  orange  cow

In [ ]:
# to store the above in a file
# df.to_csv('test3.csv') --> if we assigned df to a vairable df
(pd.read_csv(StringIO(data),usecols=['b','c'],index_col=False)).to_csv('test3.csv')

# Read Jsaon to CSV

In [85]:
data = '{"empname":"mazhar","emailId":"test@gmail.com","jobprofile":[{"jobtitle1":"TeamLeader","jobtitle2":"AIMLEnginner"}]}'
print(data)

{"empname":"mazhar","emailId":"test@gmail.com","jobprofile":[{"jobtitle1":"TeamLeader","jobtitle2":"AIMLEnginner"}]}

In [88]:
#df1 = pd.read_json("data")
#print(df1)