In [4]:
import pandas as pd
import numpy as np

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\User\anaconda3\envs\myagenticai\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\User\anaconda3\envs\myagenticai\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\User\anaconda3\envs\myagenticai\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\User\anaconda3\envs\myagenticai\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\User\anaconda3\envs\myagenticai\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [12]:
# creating a dataframe with the help of numpy
df= pd.DataFrame(np.arange(0,20).reshape(5,4))
df

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [16]:
# giving names to Rows and columns
df= pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','ROw5'],columns=['Col1','Col2','Col3','Col4'])
print(df)

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
ROw5    16    17    18    19

In [22]:
# Save the data frame as csv file, the file will be add in the folder
df.to_csv("myDataFrame.csv")

In [ ]:
# to access the elements of the dataframe
# there are two options
# 1) .loc  --> this can handle strings, Rows, columns
# 2). iloc --> this can handle only integers.(position of index)

print(df['Col1'])

Row1     0
Row2     4
Row3     8
Row4    12
ROw5    16
Name: Col1, dtype: int64

In [26]:
print(df.loc['Row1'])

Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int64

In [30]:
df.loc[:,:]

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
ROw5    16    17    18    19

In [36]:
df.loc['Row1':'Row2',:]

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7

In [37]:
df.loc[:,'Col1':'Col2']

      Col1  Col2
Row1     0     1
Row2     4     5
Row3     8     9
Row4    12    13
ROw5    16    17

In [35]:
df.loc['Row1':'Row2','Col1':'Col2']

      Col1  Col2
Row1     0     1
Row2     4     5